# Init pose
INIT_X: -36.5896222
INIT_Y: 0.5705499
INIT_Z: 0.0 
INIT_ROLL: 0.0
INIT_PITCH: 0.0
INIT_YAW: 3.14

# Parameters
INIT_SIGMA: 0.00001
SIGMA_IMU: 0.0001
SIGMA_ODOM: 0.0001
SIGMA_NDT: 0.0001

#MOTION_NOISE_NN: 0.01
#MOTION_NOISE_NO: 0.001
#MOTION_NOISE_ON: 0.0001
#MOTION_NOISE_OO: 0.0001